// <auto-generated />
using System;
using JourneyBook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JourneyBook.Infrastructure.Migrations
{
    [DbContext(typeof(JourneyBookDbContext))]
    [Migration("20260624185507_Stage2Persistence")]
    partial class Stage2Persistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasExtent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Bounds")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("AtlasExtents");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Bounds")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("NeighborEast")
                        .HasColumnType("text");

                    b.Property<string>("NeighborNorth")
                        .HasColumnType("text");

                    b.Property<string>("NeighborSouth")
                        .HasColumnType("text");

                    b.Property<string>("NeighborWest")
                        .HasColumnType("text");

                    b.Property<Guid>("PageGridId")
                        .HasColumnType("uuid");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PageGridId", "Label")
                        .IsUnique();

                    b.ToTable("AtlasPages");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasPageGrid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Overlap")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<string>("ScalePresetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("ScalePresetId");

                    b.ToTable("AtlasPageGrids");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.GeneratedPdf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceMetadataSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeneratedPdfs");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.ImportantLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GeocodeProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GeocodedFrom")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("LocationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceConfidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "LocationNumber")
                        .IsUnique();

                    b.ToTable("ImportantLocations");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.ScalePreset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Ratio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ScalePresets");

                    b.HasData(
                        new
                        {
                            Id = "usgs-7-5-min",
                            Label = "7.5-minute (1:24,000)",
                            Ratio = 24000
                        },
                        new
                        {
                            Id = "1-25000",
                            Label = "1:25,000",
                            Ratio = 25000
                        },
                        new
                        {
                            Id = "usgs-15-min",
                            Label = "15-minute (1:62,500)",
                            Ratio = 62500
                        },
                        new
                        {
                            Id = "1-50000",
                            Label = "1:50,000",
                            Ratio = 50000
                        },
                        new
                        {
                            Id = "1-100000",
                            Label = "1:100,000",
                            Ratio = 100000
                        });
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.TileSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaxZoom")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("SourceDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Version")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("TileSources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Attribution = "USGS The National Map",
                            Key = "usgs-topo",
                            MaxZoom = 16,
                            Provider = "USGS",
                            SourceUrl = "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}"
                        });
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasExtent", b =>
                {
                    b.HasOne("JourneyBook.Domain.Entities.Project", "Project")
                        .WithOne("Extent")
                        .HasForeignKey("JourneyBook.Domain.Entities.AtlasExtent", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasPage", b =>
                {
                    b.HasOne("JourneyBook.Domain.Entities.AtlasPageGrid", "PageGrid")
                        .WithMany("Pages")
                        .HasForeignKey("PageGridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageGrid");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasPageGrid", b =>
                {
                    b.HasOne("JourneyBook.Domain.Entities.Project", "Project")
                        .WithOne("PageGrid")
                        .HasForeignKey("JourneyBook.Domain.Entities.AtlasPageGrid", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JourneyBook.Domain.Entities.ScalePreset", "ScalePreset")
                        .WithMany()
                        .HasForeignKey("ScalePresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("JourneyBook.Domain.ValueObjects.PageMargins", "Margins", b1 =>
                        {
                            b1.Property<Guid>("AtlasPageGridId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Bottom")
                                .HasColumnType("double precision");

                            b1.Property<double>("Gutter")
                                .HasColumnType("double precision");

                            b1.Property<double>("Left")
                                .HasColumnType("double precision");

                            b1.Property<double>("Right")
                                .HasColumnType("double precision");

                            b1.Property<double>("Top")
                                .HasColumnType("double precision");

                            b1.HasKey("AtlasPageGridId");

                            b1.ToTable("AtlasPageGrids");

                            b1.WithOwner()
                                .HasForeignKey("AtlasPageGridId");
                        });

                    b.Navigation("Margins")
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ScalePreset");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.GeneratedPdf", b =>
                {
                    b.HasOne("JourneyBook.Domain.Entities.Project", "Project")
                        .WithMany("GeneratedPdfs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.ImportantLocation", b =>
                {
                    b.HasOne("JourneyBook.Domain.Entities.Project", "Project")
                        .WithMany("Locations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.TileSource", b =>
                {
                    b.OwnsOne("JourneyBook.Domain.ValueObjects.TileCachePolicy", "Cache", b1 =>
                        {
                            b1.Property<Guid>("TileSourceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxAgeSeconds")
                                .HasColumnType("integer");

                            b1.Property<bool>("OfflineAllowed")
                                .HasColumnType("boolean");

                            b1.HasKey("TileSourceId");

                            b1.ToTable("TileSources");

                            b1.WithOwner()
                                .HasForeignKey("TileSourceId");

                            b1.HasData(
                                new
                                {
                                    TileSourceId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    MaxAgeSeconds = 86400,
                                    OfflineAllowed = false
                                });
                        });

                    b.Navigation("Cache")
                        .IsRequired();
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.AtlasPageGrid", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("JourneyBook.Domain.Entities.Project", b =>
                {
                    b.Navigation("Extent");

                    b.Navigation("GeneratedPdfs");

                    b.Navigation("Locations");

                    b.Navigation("PageGrid");
                });
#pragma warning restore 612, 618
        }
    }
}
