import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { AtlasContract } from "./index.js";
import { LETTER_PORTRAIT, mapBoxInches } from "./page.js";
import { geodesicDistanceMeters } from "./projection.js";
import { validateAtlas, type PrintedMapBox } from "./validation.js";

/**
 * Golden fixture: a known-good 2x2 atlas the harness must keep accepting.
 *
 * Its only assertion used to be `validateAtlas(contract).pass`, which inherited
 * that function's tautology wholesale — the pre-2026-09-09 `validateAtlas`
 * compared the contract with itself, so this test would have accepted a freshly
 * generated *wrong* atlas as readily as the right one. A golden file whose test
 * cannot tell the two apart is a file, not a fixture.
 *
 * So the numbers are pinned. `scripts/regenerate-sample-atlas.mjs` rebuilds the
 * file from its recorded parameters (bbox [-98.03, 40.97, -97.97, 41.03] at
 * 1:24,000, tier 2, Letter portrait) and reproduces it byte for byte; `--check`
 * fails if it would not. If the engine changes, both this test and that check
 * fail together, and the fixture is deliberately re-approved rather than
 * silently regenerated.
 */

const FIXTURE = fileURLToPath(new URL("../../../data/fixtures/sample-atlas.json", import.meta.url));

/**
 * Every page bbox, to ten decimal places (about 10 µm of latitude). This is the
 * golden part of the golden fixture: an atlas regenerated by a broken engine
 * fails here even if it is internally consistent enough to satisfy every other
 * check in this file.
 */
const EXPECTED_BBOXES: Record<string, [number, number, number, number]> = {
  A1: [-98.04178198725921, 41.00000019820921, -97.9999933855002, 41.0418553913034],
  A2: [-98.0000066144998, 41.00000019820921, -97.9582180127408, 41.0418553913034],
  B1: [-98.04175555470597, 40.95814470297661, -97.9999933994129, 41.00000020099488],
  B2: [-98.00000660058711, 40.95814470297661, -97.95824444529403, 41.00000020099488],
};

function loadFixture(): AtlasContract {
  return JSON.parse(readFileSync(FIXTURE, "utf8").replace(/^﻿/, "")) as AtlasContract;
}

describe("golden fixture", () => {
  it("is the 2x2 grid it has always been, at the scale it has always been", () => {
    const contract = loadFixture();
    expect(contract.version).toBe(1);
    expect(contract.scale.id).toBe("usgs-7-5-min");
    expect(contract.scale.ratio).toBe(24000);
    expect(contract.margins).toEqual({ top: 0.5, right: 0.5, bottom: 0.5, left: 0.5 });
    expect(contract.pages).toHaveLength(4);
    expect(contract.pages.map((p) => p.id)).toEqual(["A1", "A2", "B1", "B2"]);
    for (const page of contract.pages) {
      expect(page.orientation).toBe("portrait");
      expect(page.tier).toBe(2);
    }
  });

  it("has exactly the page bboxes it was generated with", () => {
    for (const page of loadFixture().pages) {
      const want = EXPECTED_BBOXES[page.id];
      expect(want, `unexpected page id ${page.id}`).toBeDefined();
      for (let i = 0; i < 4; i++) {
        expect(page.bbox[i], `${page.id}.bbox[${i}]`).toBeCloseTo(want![i]!, 10);
      }
    }
  });

  it("tiles: the four pages share their interior edges and cover one rectangle", () => {
    const by = Object.fromEntries(loadFixture().pages.map((p) => [p.id, p]));
    const [a1, a2, b1, b2] = [by.A1!, by.A2!, by.B1!, by.B2!];

    // Seams are measured in metres of ground, not degrees: neighbouring pages
    // are each built about their own centre, so the shared edge carries a small
    // geodesic-vs-planar residual. A couple of metres is that residual; a page
    // width is a missing or duplicated page.
    const SEAM_TOLERANCE_M = 5;
    const eastWest = (a: number, b: number, lat: number) =>
      geodesicDistanceMeters({ lng: a, lat }, { lng: b, lat });
    const northSouth = (a: number, b: number, lng: number) =>
      geodesicDistanceMeters({ lng, lat: a }, { lng, lat: b });

    // West/east seam, on both rows.
    expect(eastWest(a1.bbox[2], a2.bbox[0], 41)).toBeLessThan(SEAM_TOLERANCE_M);
    expect(eastWest(b1.bbox[2], b2.bbox[0], 41)).toBeLessThan(SEAM_TOLERANCE_M);
    // North/south seam, in both columns.
    expect(northSouth(a1.bbox[1], b1.bbox[3], -98)).toBeLessThan(SEAM_TOLERANCE_M);
    expect(northSouth(a2.bbox[1], b2.bbox[3], -98)).toBeLessThan(SEAM_TOLERANCE_M);
    // The rows line up with each other, and the columns with each other.
    expect(northSouth(a1.bbox[3], a2.bbox[3], -98)).toBeLessThan(SEAM_TOLERANCE_M);
    expect(northSouth(b1.bbox[1], b2.bbox[1], -98)).toBeLessThan(SEAM_TOLERANCE_M);
    // No gaps and no overlap: the seam sits on the extent's centre meridian.
    expect(a1.bbox[2]).toBeCloseTo(-98, 4);
    expect(a1.bbox[1]).toBeCloseTo(41, 4);
  });

  it("covers, on the ground, exactly what 1:24,000 on a Letter map box covers", () => {
    // Independent of `validateAtlas`: measure each page geodesically and compare
    // with the printed map box times the scale denominator. This is the check
    // that would catch an atlas regenerated at the wrong scale.
    const contract = loadFixture();
    const box = mapBoxInches(LETTER_PORTRAIT);
    const expectWidth = box.widthIn * 0.0254 * 24000;
    const expectHeight = box.heightIn * 0.0254 * 24000;

    for (const page of contract.pages) {
      const [west, south, east, north] = page.bbox;
      const midLat = (south + north) / 2;
      const midLng = (west + east) / 2;
      const width = geodesicDistanceMeters({ lng: west, lat: midLat }, { lng: east, lat: midLat });
      const height = geodesicDistanceMeters({ lng: midLng, lat: south }, { lng: midLng, lat: north });
      expect(Math.abs(width / expectWidth - 1), `${page.id} width`).toBeLessThan(0.005);
      expect(Math.abs(height / expectHeight - 1), `${page.id} height`).toBeLessThan(0.005);
    }
  });

  it("passes validation, including the printed-scale check", () => {
    const contract = loadFixture();
    const box = mapBoxInches(LETTER_PORTRAIT);
    const printed: PrintedMapBox = { widthPt: box.widthIn * 72, heightPt: box.heightIn * 72 };
    const printedMapBoxes = Object.fromEntries(contract.pages.map((p) => [p.id, printed]));

    const report = validateAtlas(contract, { printedMapBoxes });
    expect(report.unmeasured).toEqual([]);
    for (const check of report.checks) {
      expect(check.pass, `${check.name}: ${check.detail}`).toBe(true);
    }
    expect(report.pass).toBe(true);
  });
});
